#!/hive/sbin/bash

#Not implemented, missing dos2unix
#not really needed in ASIC
exit 0

[[ -z $1 ]] && echo "No file given" && exit 1

for var in "$@"
do
	fname="$var"
	fname=`realpath "$fname"`

	[[ ! -f $fname ]] && echo "No such file" && exit 1


	#ensure we have Windows file
	crlf=`grep -U $'\x0D' $fname | wc -l`

	[[ $crlf -gt 0 ]] &&
		#echo "Converting $fname to unix" &&
		dos2unix $fname
done



#another example to convert
#tr -d '\r' < /hive-config/network/http_proxy.txt > /tmp/http_proxy.txt
